export const siteConfig = {
  name: 'Swift Launch',
  tagline: 'Launch faster',
  description: 'The NextJS boilerplate with all you need to build your SaaS, AI tool, or any other web app and make your first $ online fast.',
  url: process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000',
  ogImage: `${process.env.NEXT_PUBLIC_APP_URL}/og.jpg`,
  links: {
    twitter: 'https://twitter.com/yourusername',
    github: 'https://github.com/yourusername/yourrepo',
  },
  highlights: [
    { label: 'Active Users', value: '10K+' },
    { label: 'Projects Created', value: '50K+' },
    { label: 'Uptime', value: '99.9%' },
  ],
  contactChannels: [
    { label: 'Sales', value: 'sales@swiftlaunch.com' },
    { label: 'Support', value: 'support@swiftlaunch.com' },
    { label: 'Phone', value: '+1 (555) 123-4567' },
  ],
  pricingPlans: [
    {
      id: 'starter',
      name: 'Starter',
      description: 'Perfect for indie developers and small projects',
      priceMonthly: 99,
      priceLabel: '$99',
      bestFor: 'Best for individual developers',
      ctaLabel: 'Get Started',
      highlight: false,
      features: [
        'Complete Next.js 14 boilerplate',
        'TypeScript configuration',
        'Tailwind CSS + shadcn/ui',
        'Authentication system',
        'Basic payment integration',
        'Email templates',
        'Database setup',
        '6 months of updates',
      ],
    },
    {
      id: 'pro',
      name: 'Pro',
      description: 'For serious developers building to scale',
      priceMonthly: 199,
      priceLabel: '$199',
      bestFor: 'Best for growing teams',
      ctaLabel: 'Get Pro',
      highlight: true,
      features: [
        'Everything in Starter',
        'Advanced dashboard templates',
        'Admin panel components',
        'Multi-tenant architecture',
        'Advanced analytics setup',
        'SEO optimization',
        'Priority support',
        '12 months of updates',
        'Deployment guides',
      ],
    },
    {
      id: 'enterprise',
      name: 'Enterprise',
      description: 'For teams and agencies building multiple projects',
      priceMonthly: 399,
      priceLabel: '$399',
      bestFor: 'Best for agencies',
      ctaLabel: 'Contact Sales',
      highlight: false,
      features: [
        'Everything in Pro',
        'White-label license',
        'Custom integrations',
        'Team collaboration features',
        'Advanced security features',
        'Custom components library',
        'Dedicated support',
        'Lifetime updates',
        '1-on-1 setup call',
      ],
    },
  ],
  blogPosts: [
    {
      slug: 'getting-started-with-nextjs',
      title: 'Getting Started with Next.js 14',
      summary: 'Learn how to build modern web applications with Next.js 14 and the App Router.',
      category: 'Tutorial',
      publishedOn: '2024-01-15',
      readingTime: '5 min read',
      content: 'Full blog post content goes here...',
    },
    {
      slug: 'building-saas-products',
      title: 'Building SaaS Products That Scale',
      summary: 'Best practices for building scalable SaaS applications from day one.',
      category: 'Guide',
      publishedOn: '2024-01-10',
      readingTime: '8 min read',
      content: 'Full blog post content goes here...',
    },
    {
      slug: 'stripe-integration-guide',
      title: 'Complete Guide to Stripe Integration',
      summary: 'Step-by-step guide to integrating Stripe payments into your Next.js application.',
      category: 'Tutorial',
      publishedOn: '2024-01-05',
      readingTime: '10 min read',
      content: 'Full blog post content goes here...',
    },
  ],
}
